### ISSUE TITLE
May you consider to borrow some ideas from `sQ` ?

### ISSUE THREAD

**Issue by eldipa** [ArgiesDario/pytholenium#1]
This is a shameless marketing op from my side, sorry!
But I found `pythonlenium` quite similar in spirit to [sQ](https://github.com/SelectQuery/sQ/)

Both use `Selenium` to control a browser from Python: one selects elements using `dict`, the other allows you to build xpath expressions to select them.

```python
>>> from selectq import open_browser

>>> sQ = open_browser('https://books.toscrape.com/',  .....)

>>> sQ.select('tr').select('th').text()
['UPC',
 'Product Type',
 'Price (excl. tax)',
 'Price (incl. tax)',
 'Tax',
 'Availability',
 'Number of reviews']
```

Feel free to discard this issue if you are not interested. I did it with the only intention to share technology.

**Comment by ArgiesDario** [comment]
Hey, it looks interesting, I will take a deeper look at some point in order to enhance this project

Thanks for sharing!
